### ISSUE TITLE
iOS plugin is implemented incorrectly

### ISSUE THREAD

**Issue by artsemionov** [muslimtv/flutter_playout#10]
Hi,
Thank you for the nice plugin. However iOS part is implemented incorrectly - it recreates native view every time flutter rebuilds widgets. 
For example I have animation that rebuilds all widgets and plugin creates new native iOS view on every frame. In 1 second I have like 20 instances of player playing the same video, sound begin overlap and shuttering appears.
What you should doing is create player instance in `init(frame:CGRect... ` and just return created view in `view()` then it works as expected.

**Comment by KhuramKhalid** [comment]
Many thanks for that. It was such an obvious thing I missed. I've published v1.0.18 moving the init code outside of build. Please use that and let me know if there are any issues.

**Comment by artsemionov** [comment]
Hi,
Thank you for such fast response.
I see you changed the Dart side and not the native side. At first I thought it was also a way to fix this but it's still not working right.
Before, rebuilding the widget tree was calling plugin build method too, now it's not (just the didUpdateWidget()), which is a good thing.
I don't understand why but parent rebuilding calls native view() method every time (while not calling the build(), which creates new player instances every frame. I checked this by adding a print to this method. It seems that native views working like this in flutter, so I believe a good way to fix this is to change native part of the plugin, creating player in init() and just returning it in view().
Before you make an update please read another Issue I want to create now.

**Comment by real1900** [comment]
Looks like this issue is still open .

@artsemionov Do you have a working version of the correct code for iOS ? I am facing the same issue.

**Comment by real1900** [comment]
[VideoPlayer.swift.zip](https://github.com/muslimtv/flutter_playout/files/4364714/VideoPlayer.swift.zip)

Does this implementation look correct ? @artsemionov ?

**Comment by real1900** [comment]
That works for me

**Comment by skytz** [comment]
@real1900 I tested your changes in VideoPlayer.swift and it seems to be working.
Made a PR with it: https://github.com/muslimtv/flutter_playout/pull/29

**Comment by KhuramKhalid** [comment]
There has been a slight change in iOS native implementation in regards to player setup. See #41.
